"""from-which-site

Revision ID: a6e8688723e8
Revises: 10ed2355f12e
Create Date: 2024-11-06 13:32:00.015990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e8688723e8'
down_revision = '10ed2355f12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('from',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_site', sa.String(length=40), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('from')
    # ### end Alembic commands ###
