"""replace img with video

Revision ID: c390bf413bd9
Revises: b752c6134b35
Create Date: 2024-12-16 10:01:35.296168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c390bf413bd9'
down_revision = 'b752c6134b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('por', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_src', sa.String(length=60), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('por', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('video_src')

    # ### end Alembic commands ###
