"""empty message

Revision ID: ede0eca93d7e
Revises: 1578a540f2dc
Create Date: 2024-12-23 22:35:38.577830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede0eca93d7e'
down_revision = '1578a540f2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('por', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_scr', sa.String(length=60), nullable=True))
        batch_op.drop_column('video_src')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('por', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_src', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_column('img_scr')

    # ### end Alembic commands ###
