"""filter to Por

Revision ID: fadee8f9751c
Revises: 3fd0291c6492
Create Date: 2024-12-15 11:06:29.949132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadee8f9751c'
down_revision = '3fd0291c6492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('por', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('por', schema=None) as batch_op:
        batch_op.drop_column('filter')

    # ### end Alembic commands ###
